<?php
namespace App\Services\Constants;

class CountryConstant{
    public const COUNTRIES = array(
        'Argentina',
        'Australia',
        'Austria',
        'Belgium',
        'Brazil',
        'Bulgaria',
        'Canada',
        'Chile',
        'Colombia',
        'Croatia',
        'Cyprus',
        'Czech Republic',
        'Denmark',
        'Estonia',
        'Finland',
        'France',
        'Germany',
        'Greece',
        'Hong Kong',
        'Hungary',
        'Ireland',
        'Israel',
        'Italy',
        'Japan',
        'Latvia',
        'Lithuania',
        'Luxembourg',
        'Malta',
        'Mexico',
        'Netherlands',
        'New Zealand',
        'Norway',
        'Peru',
        'Poland',
        'Portugal',
        'Romania',
        'Russia',
        'Slovakia',
        'Slovenia',
        'South Africa',
        'Spain',
        'Sweden',
        'Switzerland',
        'United Kingdom',
        'United States'
    );
}
